---
title: "Homework 2: Finding Your Way in R and Python"
author: "Your Name"
output: html_document
---

# MadLibs

## Running a Python Script at the command line

Run the script [madlibs.py](madlibs.py) at the command line. Do what it asks of you, and then paste the output here, making use of the generic (no language) markdown code chunk below.

    susan@silicon:~/Projects/Class/unl-stat850/2022-Homework/02-FindingYourWay$ python3 madlibs.py
    Choose a noun: dinosaur
    Choose a plural noun: animals
    Choose a noun: friend
    Name a place: school
    Choose an adjective (Describing word): variable
    Choose a noun: homework
    ------------------------------------------
    Be kind to your dinosaur- footed animals
    For a duck may be somebody's friend,
    Be kind to your animals in school
    Where the weather is always variable.

    You may think that is this the homework,
    Well it is.
    ------------------------------------------

## Running a Python Script in RStudio using "Source Script"

Can you run this same script in RStudio using the Source Script button? If you can, please describe any differences you note compared to using the terminal. If you cannot, tell me what happens.

Paste any relevant output here:

    R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
    Copyright (C) 2022 The R Foundation for Statistical Computing
    Platform: x86_64-pc-linux-gnu (64-bit)

    R is free software and comes with ABSOLUTELY NO WARRANTY.
    You are welcome to redistribute it under certain conditions.
    Type 'license()' or 'licence()' for distribution details.

      Natural language support but running in an English locale

    R is a collaborative project with many contributors.
    Type 'contributors()' for more information and
    'citation()' on how to cite R or R packages in publications.

    Type 'demo()' for some demos, 'help()' for on-line help, or
    'help.start()' for an HTML browser interface to help.
    Type 'q()' to quit R.

    > reticulate::source_python('~/Projects/Class/unl-stat850/2022-Homework/02-FindingYourWay/madlibs.py')
    Choose a noun: dog
    Choose a plural noun: dogs
    Choose a noun: friend
    Name a place: Nebraska
    Choose an adjective (Describing word): crazy
    Choose a noun: assignment
    ------------------------------------------
    Be kind to your dog- footed dogs
    For a duck may be somebody's friend,
    Be kind to your dogs in Nebraska
    Where the weather is always crazy.

    You may think that is this the assignment,
    Well it is.
    ------------------------------------------

The script runs approximately the same except that instead of running in the terminal, it runs in the R console, and appears to run in R instead of the command line. There is an additional line (`reticulate::source_python(...)`) that suggests that R is running python code through the use of an additional program. Otherwise, the interface itself is the same.
